package pub

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestHeader(t *testing.T) {

	header := `keyId="http://localhost/@63810ba2721f7a33807f25c7/pub/key",algorithm="hs2019",headers="(request-target) host date",signature="Kcn3TRZLmwIAsEY3HGL5gP4BKU5uJ9Qhm2kBSxjLOyG2//soTSAuld1RbNhlm4Fz9twgt5GlkP1Ppeno1mP8VzhM4KhhXnr9a8Bd+Ti9gIv4EHeJeKRCURy6PTMqsbbGR37s3Nif/UQAjUWy2q63klINeB+L4W1g38vTxu1m9NiCXBdgMuyFHbXhxnFzpNstFXxfr+Mx9+rbmxUWtqMKj4Zh7dedqD0g/nDPTPbYFKNWOgYfBFwbyl3gRrWgavkyP7L/qeNYnkB98ACWdQwGGJQ1Fi4JQQxXxtAVbOKgBRFMLGn/jH8yYxzrW5OILznvJS7pzFgYsnzomVbaAdYkSA=="`
	result := ParseSignatureHeader(header)

	require.Equal(t, "http://localhost/@63810ba2721f7a33807f25c7/pub/key", result["keyId"])
	require.Equal(t, "hs2019", result["algorithm"])
	require.Equal(t, "(request-target) host date", result["headers"])
	require.Equal(t, "Kcn3TRZLmwIAsEY3HGL5gP4BKU5uJ9Qhm2kBSxjLOyG2//soTSAuld1RbNhlm4Fz9twgt5GlkP1Ppeno1mP8VzhM4KhhXnr9a8Bd+Ti9gIv4EHeJeKRCURy6PTMqsbbGR37s3Nif/UQAjUWy2q63klINeB+L4W1g38vTxu1m9NiCXBdgMuyFHbXhxnFzpNstFXxfr+Mx9+rbmxUWtqMKj4Zh7dedqD0g/nDPTPbYFKNWOgYfBFwbyl3gRrWgavkyP7L/qeNYnkB98ACWdQwGGJQ1Fi4JQQxXxtAVbOKgBRFMLGn/jH8yYxzrW5OILznvJS7pzFgYsnzomVbaAdYkSA==", result["signature"])
}

// This is a key generated by Emissary
func TestParseRSAKey(t *testing.T) {

	// hs2019 certs
	cert := "-----BEGIN RSA PUBLIC KEY-----\nMIIBCgKCAQEAlifIuRIJII6Z1FblKF0XD17nTCYP+AdX+9KXJ2/WOfxs2/CTVFGa\nq0ovIdoDK2jydatRciYmwYYS+xrixzvPdUqN3Kcpev1MwUqQuThVy3QiJAI0sJ0L\nJzruzZKXt8q3YbuWcMiNwfOv0/+VpsZHa7yltxFKHiULIBz/dF/0t3ulwGeUpVGA\nQrH0uWfmPs8hPkaIs8IIgEFGyUjPHejK+jZaqUSxbBlpzvnaEgKEJVXYawHCUipF\nQp5N1zdXi+FNNuERqixWHdmyguNWTLdwmH9bq1nFe6pLDG4eqXnEGFDXXZ90SQhe\nsfEDVzm0Yzcv7wkJFm80aPDsa7Y+IARddwIDAQAB\n-----END RSA PUBLIC KEY-----\n"
	key, err := ParsePublicKeyFromPEM(cert)

	require.Nil(t, err)
	require.NotNil(t, key)
}

// This is a public key from a Mastodon instance
func TestParseRSAKey2(t *testing.T) {

	cert := "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApIC6kVMMkk0cc4GCAQ+/\n5XAKz8KhSbSpsWFC1jVRH+AXDAH3O6Pw+r5xNUu+OEGUPnLXycxuPZapxTQPGw/w\nPUMk2QvEhi9WEECrdPG8y2dEZMcNvGhtOtyhIWHGBLfANcpeueW3Z8WBR2Eak5+Y\nkuy+oiS3CZ13JAxbY6AfNc6L1V1G1hSppoynBhxdk1V9XbSLGSPEcL0ZTKS2Jo9Y\nB/ipPTWWpD1jHvELTNEsgfcAgAmHsEIH7j9RhMy/YtsOczlymf+fqvcy5NJHzAaV\nFRomn/Eci/IYKGTc6/g3AzVQZ0aILEArgwiAUoumiWqco+ASVsjDY5by3Yxx3vsA\n+QIDAQAB\n-----END PUBLIC KEY-----\n"

	key, err := ParsePublicKeyFromPEM(cert)

	require.Nil(t, err)
	require.NotNil(t, key)
}

// This is a key from an example I found on the Internet
func TestPKIXKey(t *testing.T) {
	cert := `-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAlRuRnThUjU8/prwYxbty
WPT9pURI3lbsKMiB6Fn/VHOKE13p4D8xgOCADpdRagdT6n4etr9atzDKUSvpMtR3
CP5noNc97WiNCggBjVWhs7szEe8ugyqF23XwpHQ6uV1LKH50m92MbOWfCtjU9p/x
qhNpQQ1AZhqNy5Gevap5k8XzRmjSldNAFZMY7Yv3Gi+nyCwGwpVtBUwhuLzgNFK/
yDtw2WcWmUU7NuC8Q6MWvPebxVtCfVp/iQU6q60yyt6aGOBkhAX0LpKAEhKidixY
nP9PNVBvxgu3XZ4P36gZV6+ummKdBVnc3NqwBLu5+CcdRdusmHPHd5pHf4/38Z3/
6qU2a/fPvWzceVTEgZ47QjFMTCTmCwNt29cvi7zZeQzjtwQgn4ipN9NibRH/Ax/q
TbIzHfrJ1xa2RteWSdFjwtxi9C20HUkjXSeI4YlzQMH0fPX6KCE7aVePTOnB69I/
a9/q96DiXZajwlpq3wFctrs1oXqBp5DVrCIj8hU2wNgB7LtQ1mCtsYz//heai0K9
PhE4X6hiE0YmeAZjR0uHl8M/5aW9xCoJ72+12kKpWAa0SFRWLy6FejNYCYpkupVJ
yecLk/4L1W0l6jQQZnWErXZYe0PNFcmwGXy1Rep83kfBRNKRy5tvocalLlwXLdUk
AIU+2GKjyT3iMuzZxxFxPFMCAwEAAQ==
-----END PUBLIC KEY-----`

	key, err := ParsePublicKeyFromPEM(cert)
	require.Nil(t, err)
	require.NotNil(t, key)
}
